version: '3.7'

services:
  qlhs-frontend-client:
    stdin_open: true
    image: qlhs-frontend-client:${version}
    container_name: qlhs-frontend-client-${version}
    restart: always
    command: ${command}
    ports:
      - 17012:17012
    build:
      context: ./
      dockerfile: Dockerfile
    # networks:
    #   default:
    #     ipv4_address: 192.168.0.100
# Network
# networks:
#   default:
#     external: true
#     name: qlhs-microservices-network.local